# Generated by Django 5.1.6 on 2025-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_goal_buffer_goal_buffer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
