# Generated by Django 5.1.6 on 2025-03-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_account_user_alter_account_alias_alter_goal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
